config/routes.rb
Rails.application.routes.draw do
  root to: "countries#index"
  resources :countries, only: [:index] do
    collection do
      get "search"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all.order("name ASC").paginate(:page => params[:page], :per_page => 20)
    if params[:select2]
      @countries_for_select2 = CountryLookup.new.call(country_params)
      render 'search'
    end
  end

  def search
    @countries_for_select2 = CountryLookup.new.call(country_params)
    render @countries_for_select
  end

  private

  def country_params
    params.permit(:name, :phone_code, :timezone, :currency_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/countries/_countries_for_select2.html.erb
<p id="notice"><%= notice %></p>
<div class="allcontain">
<h1>Countries</h1>

  <table data-toggle="table" width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead style= "background-color: #bdacac; font-family: 'Liberation Sans';font-size: 12.7px">
    <tr class="text-gray">
      <th>Name</th>
      <th data-sortable="true">Population</th>
      <th>Phone Code</th>
      <th>Currency Code</th>
      <th>Timezone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries_for_select2.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.population %></td>
        <td><%= country.phone_code %></td>
        <td><%= country.currency_code %></td>
        <td><%= country.timezone %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<div class="form-control">
<%= link_to 'Back', root_path %>
</div>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>
<div class="allcontain">
<h2>Countries</h2>
<%= react_component 'Countries', { data: @countries } %>

  <table data-toggle="table" width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead style= "background-color: #d1cdc2; font-family: 'Liberation Sans'; font-size: 12.2px;">
    <tr class="text-gray">
      <th>Name</th>
      <th data-sortable="true">Population</th>
      <th>Phone Code</th>
      <th>Currency Code</th>
      <th>Timezone</th>
    </tr>
  </thead>

  <tbody style= "font-size: 85%;">
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.population %></td>
        <td><%= country.phone_code %></td>
        <td><%= country.currency_code %></td>
        <td><%= country.timezone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <%= form_tag(search_countries_path, method: :get) do %>
  <%= label_tag("Find by code")%>
  <%= select_tag("phone_code", options_from_collection_for_select(Country.all, :phone_code, :phone_code), class: "select2", id: "select-single", :include_blank => true, data: {placeholder: "Choose a Country"}) %>
  <%= submit_tag("Search", class: "btn btn-primary") %>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    $('.select-single').select2({
    placeholder: "Choose a country",
    allowClear: true
  });
});
</script>
<%= will_paginate @countries %>

app/views/countries/search.html.erb
<%= render partial: 'countries_for_select2' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Country List</title>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag('jquery.js') %>
    <%= javascript_include_tag('bootstrap.js') %>
  </head>

  <body>
    <div class="allcontain">
	   <div class="header">
      <%= form_tag(search_countries_url, method: :get) do %>
       <%= label_tag("Choose a country")%>
       <%= select_tag("name", options_from_collection_for_select(Country.all, :name, :name), class: "select2", :include_blank => true, data: {placeholder: "Choose a Country"}) %>
       <%= submit_tag("Search", class: "btn btn-primary") %>
      <% end %>
     </div>
    </div>
    <%= yield %>
  </body>
</html>